config/routes.rb
Rails.application.routes.draw do
  resources :entries do
    resources :entry_items
  end
  resources :accounts
  root 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
# Accounts group entries together
class Account < ApplicationRecord
  has_many :entry_items, dependent: :destroy
  has_many :entries, through: :entry_items

  def credit_total
    entry_items.where(type: 'EntryItems::Credit').sum(:amount)
  end

  def debit_total
    entry_items.where(type: 'EntryItems::Debit').sum(:amount)
  end

  def balance
    debit_total - credit_total
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
# Each individual entry
class Entry < ApplicationRecord
  has_many :entry_items, dependent: :destroy

  accepts_nested_attributes_for :entry_items

  after_create :set_entry_items

  attr_accessor :credit_account_id, :debit_account_id

  def set_entry_items
    entry_items.create!(type: 'EntryItems::Credit', account_id: credit_account_id, amount: amount)
    entry_items.create!(type: 'EntryItems::Debit', account_id: debit_account_id, amount: amount)
  end
end

app/models/entry_item.rb
class EntryItem < ApplicationRecord
  belongs_to :entry
  belongs_to :account, optional: true, touch: true

  def credit?
    false
  end

  def debit?
    false
  end
end

app/models/entry_items/credit.rb
module EntryItems
  # Handles all things Credit
  class Credit < ::EntryItem
    def self.model_name
      EntryItem.model_name
    end

    def credit?
      true
    end
  end
end

app/models/entry_items/debit.rb
module EntryItems
  # Handles all things Debit
  class Debit < ::EntryItem
    def self.model_name
      EntryItem.model_name
    end

    def debit?
      true
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to accounts_path, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to accounts_path, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all.order(date: :desc)
  end

  # GET /entries/1
  # GET /entries/1.json
  def show; end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit; end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entries_path, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entries_path, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entry
    @entry = Entry.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entry_params
    params.require(:entry).permit(:debit_account_id, :credit_account_id, :name, :amount, :date)
  end
end

app/controllers/entry_items_controller.rb
class EntryItemsController < ApplicationController
  before_action :set_entry
  before_action :set_entry_item, only: [:show, :edit, :update, :destroy]

  # GET /entry_items
  # GET /entry_items.json
  def index
    @entry_items = @entry.entry_items
  end

  # GET /entry_items/1
  # GET /entry_items/1.json
  def show; end

  # GET /entry_items/new
  def new
    @entry_item = @entry.entry_items.new
  end

  # GET /entry_items/1/edit
  def edit; end

  # POST /entry_items
  # POST /entry_items.json
  def create
    @entry_item = @entry.entry_items.new(entry_item_params)

    respond_to do |format|
      if @entry_item.save
        format.html { redirect_to entry_entry_items_path(@entry), notice: 'Entry item was successfully created.' }
        format.json { render :show, status: :created, location: entry_entry_item_path(@entry, @entry_item) }
      else
        format.html { render :new }
        format.json { render json: @entry_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entry_items/1
  # PATCH/PUT /entry_items/1.json
  def update
    respond_to do |format|
      if @entry_item.update(entry_item_params)
        format.html { redirect_to entry_entry_items_path(@entry), notice: 'Entry item was successfully updated.' }
        format.json { render :show, status: :ok, location: entry_entry_item_path(@entry, @entry_item) }
      else
        format.html { render :edit }
        format.json { render json: @entry_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entry_items/1
  # DELETE /entry_items/1.json
  def destroy
    @entry_item.destroy
    respond_to do |format|
      format.html { redirect_to entry_entry_items_path(@entry), notice: 'Entry item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_entry
    @entry = Entry.find(params[:entry_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_entry_item
    @entry_item = @entry.entry_items.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entry_item_params
    params.require(:entry_item).permit(:account_id, :type, :amount)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @accounts = Account.order(updated_at: :asc).last(10)
    @entries = Entry.order(date: :desc).first(10)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
# All thing helpers
module ApplicationHelper
  def current_nav_link_class(test_path)
    return 'nav-link active' if request.path == test_path
    'nav-link'
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/entry_items_helper.rb
module EntryItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p></p>

<h1>Accounts</h1>

<p class="lead">
  Summary of all the accounts.
</p>

<% if @accounts.size.positive? %>
<div class="table-responsive mt-5">
  <table class="table table-dark table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Balance</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @accounts.each do |account| %>
        <tr>
          <td class="align-middle"><%= account.name %></td>
          <td class="align-middle"><%= number_to_currency(account.balance) %></td>
          <td><%= link_to 'View', account, class: 'btn btn-outline-primary' %></td>
          <td><%= link_to 'Edit', edit_account_path(account), class: 'btn btn-primary' %></td>
          <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
<h3>There are no accounts</h3>
<% end %>

<br>

<%= link_to 'New Account', new_account_path, class: 'btn btn-primary' %>

app/views/accounts/new.html.erb
<p></p>

<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path, class: 'btn btn-secondary' %>

app/views/accounts/show.html.erb
<p></p>

<h1><%= @account.name %></h1>

<h2>Balance: <%= number_to_currency(@account.balance) %></h2>

<p class="lead">
  Summary of all the entries for <%= @account.name %>.
</p>

<div class="table-responsive mt-5">
  <table class="table table-dark table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Name</th>
        <th>Debit</th>
        <th>Credit</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @account.entry_items.each do |entry_item| %>
        <tr>
          <td class="align-middle"><%= entry_item.entry.date %></td>
          <td class="align-middle"><%= entry_item.entry.name %></td>
          <td class="align-middle text-success"><%= entry_item.debit? ? number_to_currency(entry_item.amount) : '' %></td>
          <td class="align-middle text-danger"><%= entry_item.credit? ? number_to_currency(entry_item.amount) : '' %></td>
          <td><%= link_to 'Edit', edit_entry_path(entry_item.entry), class: 'btn btn-primary btn-sm' %></td>
          <td><%= link_to 'Destroy', entry_item.entry, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
        </tr>
      <% end %>
      <tr>
        <td colspan="2"><b>Total</b></td>
        <td class="align-middle text-success"><%= number_to_currency(@account.debit_total) %></td>
        <td class="align-middle text-danger"><%= number_to_currency(@account.credit_total) %></td>
        <td colspan="2"></td>
      </tr>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Entry', new_entry_path, class: 'btn btn-primary mb-3' %>

<br >

<%= link_to 'Edit Account', edit_account_path(@account), class: 'btn btn-primary' %>
<%= link_to 'Back', accounts_path, class: 'btn btn-secondary' %>

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading">
        <%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:
      </h4>
      <% entry.errors.full_messages.each.with_index do |message, index| %>
        <hr />
        <p class="<%= entry.errors.count == (index + 1) ? 'mb-0' : '' %>"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :date, class: 'form-label' %>
    <%= form.date_field :date, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :amount, class: 'form-label' %>
    <%= form.number_field :amount, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <a href="<%= entry_entry_items_path(@entry) %>" class="btn btn-primary btn-block">
      Manage Debits and Credits
    </a>
  </div>

  <div class="mb-3">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

<script type="text/javascript">
window.flatpickr("#entry_date", {});
</script>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<p></p>

<h1>Entries</h1>

<p class="lead">
  Summary of all the entries.
</p>

<div class="table-responsive mt-5">
  <table class="table table-dark table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Name</th>
        <th>Amount</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @entries.each do |entry| %>
        <tr>
          <td class="align-middle"><%= entry.date %></td>
          <td class="align-middle"><%= entry.name %></td>
          <td class="align-middle"><%= number_to_currency(entry.amount) %></td>
          <td class="align-middle"><%= link_to 'Edit', edit_entry_path(entry), class: 'btn btn-primary' %></td>
          <td class="align-middle"><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Entry', new_entry_path, class: 'btn btn-primary' %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= form_with(model: @entry, local: true) do |form| %>
  <% if @entry.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading">
        <%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:
      </h4>
      <% @entry.errors.full_messages.each.with_index do |message, index| %>
        <hr />
        <p class="<%= @entry.errors.count == (index + 1) ? 'mb-0' : '' %>"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :date, class: 'form-label' %>
    <%= form.date_field :date, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :amount, class: 'form-label' %>
    <%= form.number_field :amount, class: 'form-control' %>
  </div>

  <div class="row mb-3">
    <div class="col">
      <%= form.label :debit_account_id, class: 'form-label' %>
      <%= form.select :debit_account_id, Account.all.collect {|a| [ a.name, a.id ] }, { include_blank: 'N/A' }, class: 'form-select' %>
    </div>

    <div class="col">
      <%= form.label :credit_account_id, class: 'form-label' %>
      <%= form.select :credit_account_id, Account.all.collect {|a| [ a.name, a.id ] }, { include_blank: 'N/A' }, class: 'form-select' %>
    </div>
  </div>


  <div class="mb-3">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

<script type="text/javascript">
window.flatpickr("#entry_date", {});
</script>

<%= link_to 'Back', entries_path, class: 'btn btn-secondary' %>

app/views/entries/show.html.erb
<p></p>

<p>
  <strong>Debit Account:</strong>
  <%= @entry.debit_account ? @entry.debit_account.name : 'N/A' %>
</p>

<p>
  <strong>Credit Account:</strong>
  <%= @entry.credit_account ? @entry.credit_account.name : 'N/A' %>
</p>

<p>
  <strong>Name:</strong>
  <%= @entry.name %>
</p>

<p>
  <strong>Debit:</strong>
  <%= @entry.debit %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @entry.credit %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/entry_items/_form.html.erb
<%= form_with(model: [entry_item.entry, entry_item], local: true) do |form| %>
  <% if entry_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry_item.errors.count, "error") %> prohibited this entry_item from being saved:</h2>

      <ul>
        <% entry_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col">
    <%= form.label :type, class: 'form-label' %>
    <%= form.select :type, [['Debit', 'EntryItems::Debit'], ['Credit', 'EntryItems::Credit']], { include_blank: 'N/A' }, class: 'form-select' %>
  </div>

  <div class="col">
    <%= form.label :account_id, class: 'form-label' %>
    <%= form.select :account_id, Account.all.collect {|a| [ a.name, a.id ] }, { include_blank: 'N/A' }, class: 'form-select' %>
  </div>

  <div class="mb-3">
    <%= form.label :amount, class: 'form-label' %>
    <%= form.number_field :amount, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/entry_items/edit.html.erb
<h1>Editing Entry Item</h1>

<%= render 'form', entry_item: @entry_item %>

<%= link_to 'Show', entry_entry_item_path(@entry, @entry_item) %> |
<%= link_to 'Back', entry_entry_items_path(@entry) %>

app/views/entry_items/index.html.erb
<p></p>

<h1><%= @entry.name %></h1>

<p class="lead">
  Accounts debited and credited for this transaction.
</p>

<div class="table-responsive mt-5">
  <table class="table table-dark table-striped">
    <thead>
      <tr>
        <th>Account</th>
        <th>Debit</th>
        <th>Credit</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @entry_items.each do |entry_item| %>
        <tr>
          <td class="align-middle"><%= entry_item.account ? entry_item.account.name : 'N/A' %></td>
          <td class="align-middle text-success"><%= entry_item.debit? ? number_to_currency(entry_item.amount) : '' %></td>
          <td class="align-middle text-danger"><%= entry_item.credit? ? number_to_currency(entry_item.amount) : '' %></td>
          <td class="align-middle"><%= link_to 'Edit', edit_entry_entry_item_path(@entry, entry_item), class: 'btn btn-primary' %></td>
          <td class="align-middle"><%= link_to 'Destroy', entry_entry_item_path(@entry, entry_item), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Debit/Credit', new_entry_entry_item_path(@entry), class: 'btn btn-primary' %>
<%= link_to 'Back to Entry', edit_entry_path(@entry), class: 'btn btn-secondary' %>

app/views/entry_items/new.html.erb
<h1>New Entry Item</h1>

<%= render 'form', entry_item: @entry_item %>

<%= link_to 'Back', entry_entry_items_path(@entry) %>

app/views/entry_items/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_entry_entry_item_path(@entry, @entry_item) %> |
<%= link_to 'Back', entry_entry_items_path(@entry) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Entries</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#1c5f30">
    <meta name="theme-color" content="#1c5f30">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_packs_with_chunks_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_packs_with_chunks_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-dark text-light">
    <%= render partial: 'layouts/application/header' %>
    <div style="position: relative; width: 100%">
      <%= render partial: 'layouts/application/notice' %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-image: none;">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#headerToggle" aria-controls="headerToggle" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="headerToggle">
      <ul class="navbar-nav mr-auto my-2 my-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: current_nav_link_class(root_path) %>
        </li>
        <li class="nav-item">
          <%= link_to 'Accounts', accounts_path, class: current_nav_link_class(accounts_path) %>
        </li>
        <li class="nav-item">
          <%= link_to 'Entries', entries_path, class: current_nav_link_class(entries_path) %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application/_notice.html.erb
<% if notice %>
<div id="toast_notice" class="toast" role="alert" aria-live="assertive" aria-atomic="true" style="position: absolute; top: 3px; right: 3px;" data-delay="4000">
  <div class="toast-header">
    <strong class="mr-auto">Notice</strong>
    <small>Just now</small>
    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="toast-body text-dark">
    <%= notice %>
  </div>
</div>

<script>
window.onload = function loadToast() {
  if (window.Toast) {
    var toastElement = document.getElementById('toast_notice');
    var toast = new window.Toast(toastElement);
    toast.show();
  }
}
</script>
<% end %>

app/views/pages/home.html.erb
<p id="notice"><%= notice %></p>

<div class="card text-white bg-dark text-center border border-light" style="min-height: 25vh;">
  <div class="card-body d-flex justify-content-center align-items-center">
    <div>
      <h1>Accounting examples</h1>
      <p class="lead">Simple examples for how different accounting-type setups can work</p>
    </div>
  </div>
</div>

<div class="row row-cols-1 row-cols-md-2 g-4 mt-3">
  <div class="col">
    <% if @accounts.size.positive? %>
      <%= render partial: 'pages/home/accounts', locals: { accounts: @accounts } %>
    <% else %>
      <%= render partial: 'pages/home/empty_card', locals: { type: 'Accounts', path: new_account_path } %>
    <% end %>
  </div>
  <div class="col">
    <% if @accounts.size.zero? %>
      <%= render partial: 'pages/home/empty_card', locals: { type: 'Accounts', path: new_account_path } %>
    <% elsif @entries.size.positive? %>
      <%= render partial: 'pages/home/entries', locals: { entries: @entries } %>
    <% else %>
      <%= render partial: 'pages/home/empty_card', locals: { type: 'Entries', path: new_entry_path } %>
    <% end %>
  </div>
</div>

app/views/pages/home/_account.html.erb
<a class="list-group-item list-group-item-action d-flex justify-content-between bg-dark text-light" href="<%= account_path(account) %>%">
  <span class="d-flex align-items-center">
  <%= account.name %>
  <span class="badge bg-primary rounded-pill ml-1">
    <%= account.entries.size %>
  </span>
  </span>
  <%= number_to_currency(account.balance) %>
</a>

app/views/pages/home/_accounts.html.erb
<div class="card bg-dark">
  <div class="card-header">
    <strong>
      Recent accounts
    </strong>
  </div>
  <div class="list-group list-group-flush">
    <% accounts.each do |account| %>
      <% cache account do %>
        <%= render partial: 'pages/home/account', locals: { account: account } %>
      <% end %>
    <% end %>
    <div class="list-group-item bg-dark" >
      <a class="btn btn-block btn-outline-primary" href="<%= new_account_path %>">
        Add new account
      </a>
    </div>
  </div>
</div>

app/views/pages/home/_empty_card.html.erb
<div class="card bg-dark" style="min-height: 30vh">
  <div class="card-header">
    No <%= type || 'Things' %>
  </div>
  <div class="card-body d-flex flex-column justify-content-center align-items-center">
    <span class="mb-3">
      There are no <%= type || 'Things' %> yet.
    </span>
    <a href="<%= path || root_url %>" class="btn btn-primary">Add One</a>
  </div>
</div>

app/views/pages/home/_entries.html.erb
<div class="card bg-dark">
  <div class="card-header">
    <strong>
      Recent Entries
    </strong>
  </div>
  <div class="list-group list-group-flush">
    <% entries.each do |entry| %>
      <% cache entry do %>
        <%= render partial: 'pages/home/entry', locals: { entry: entry } %>
      <% end %>
    <% end %>
    <div class="list-group-item bg-dark" >
      <a class="btn btn-block btn-outline-primary" href="<%= new_entry_path %>">
        Add new entry
      </a>
    </div>
  </div>
</div>

app/views/pages/home/_entry.html.erb
<a class="list-group-item list-group-item-action d-flex justify-content-between bg-dark text-light" href="<%= edit_entry_path(entry) %>">
  <span class="d-flex align-items-center">
    <span class="badge bg-secondary mr-2">
      <%= entry.date %>
    </span>
    <%= entry.name %>
  </span>
  <%= number_to_currency(entry.amount) %>
</a>